// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoq7Ra7LRqalZqrl9WmlfK9Z91yf9mPwU',
    appId: '1:40761641715:web:48da913dbd379bca1ac586',
    messagingSenderId: '40761641715',
    projectId: 'thirdeye-7a6d6',
    authDomain: 'thirdeye-7a6d6.firebaseapp.com',
    databaseURL: 'https://thirdeye-7a6d6-default-rtdb.firebaseio.com',
    storageBucket: 'thirdeye-7a6d6.appspot.com',
    measurementId: 'G-VSYBHG3DJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC36z10TDJWWtltuJCKfcfhM61XcwQl4Do',
    appId: '1:40761641715:android:1265cfd8167e6a3a1ac586',
    messagingSenderId: '40761641715',
    projectId: 'thirdeye-7a6d6',
    databaseURL: 'https://thirdeye-7a6d6-default-rtdb.firebaseio.com',
    storageBucket: 'thirdeye-7a6d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWB_Zry_BKwZWJJpyyxNsYgT76JhetB-g',
    appId: '1:40761641715:ios:49d0669b193eb0be1ac586',
    messagingSenderId: '40761641715',
    projectId: 'thirdeye-7a6d6',
    databaseURL: 'https://thirdeye-7a6d6-default-rtdb.firebaseio.com',
    storageBucket: 'thirdeye-7a6d6.appspot.com',
    iosBundleId: 'com.example.thirdeyeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWB_Zry_BKwZWJJpyyxNsYgT76JhetB-g',
    appId: '1:40761641715:ios:7ae51cf0fd0ec0061ac586',
    messagingSenderId: '40761641715',
    projectId: 'thirdeye-7a6d6',
    databaseURL: 'https://thirdeye-7a6d6-default-rtdb.firebaseio.com',
    storageBucket: 'thirdeye-7a6d6.appspot.com',
    iosBundleId: 'com.example.thirdeyeapp.RunnerTests',
  );
}
